In [2]:
from bs4 import BeautifulSoup
import pandas as pd
import urllib
from urllib.request import urlopen

from tqdm import tqdm_notebook

chart_date = []
chart_ranking = []
chart_title = []
chart_artist = []
chart_album = []

date = pd.date_range('2016-01-12', periods=20, freq='m')

In [3]:
for today in tqdm_notebook(date):
    url = "https://music.bugs.co.kr/chart/track/day/total?chartdate={date}"
    html = url.format(date=urllib.parse.quote(today.strftime('%Y%m%d')))
    
    response = urlopen(html)
    soup = BeautifulSoup(response, 'html.parser')
    end = len( soup.find_all('p', 'title') )
    
    for n in range(end):
        artist = soup.find_all('p', 'artist')[n].a.string
        if artist == '아이유(IU)':
            chart_date.append(today)
            chart_ranking.append(soup.find_all('div', 'ranking')[n].strong.string)
            chart_title.append(soup.find_all('p', 'title')[n].a.string)
            chart_album.append(soup.find_all('a', 'album')[n+1].string)

HBox(children=(IntProgress(value=0, max=20), HTML(value='')))

In [4]:
chart = pd.DataFrame({'date': chart_date,
                     'title': chart_title,
                     'ranking': chart_ranking })
chart

         date                            title ranking
0  2016-01-31                              스물셋      53
1  2016-02-29                              스물셋      69
2  2016-11-30  미리 메리 크리스마스 (feat. 천둥 Of MBLAQ)      67
3  2016-12-31  미리 메리 크리스마스 (feat. 천둥 Of MBLAQ)      85
4  2017-03-31                              밤편지       2
5  2017-04-30             팔레트 (Feat. G-DRAGON)       1
6  2017-04-30                             이 지금       4
7  2017-04-30                  사랑이 잘 (With 오혁)       5
8  2017-04-30                            이런 엔딩       9
9  2017-04-30                              밤편지      10
10 2017-04-30                               잼잼      11
11 2017-04-30                             이름에게      14
12 2017-04-30                        Black Out      18
13 2017-04-30                              마침표      33
14 2017-04-30                          그렇게 사랑은      44
15 2017-05-31             팔레트 (Feat. G-DRAGON)      13
16 2017-05-31                  사랑이 잘 (With 오혁)      22
17 2017-05-31                              밤편지      29
18 2017-05-31                             이 지금      31
19 2017-05-31                            이런 엔딩      45
20 2017-05-31                               잼잼      67
21 2017-05-31                             이름에게     100
22 2017-06-30             팔레트 (Feat. G-DRAGON)      23
23 2017-06-30                              밤편지      32
24 2017-06-30                  사랑이 잘 (With 오혁)      41
25 2017-06-30                             이 지금      63
26 2017-06-30                            이런 엔딩      89
27 2017-07-31                              밤편지      12
28 2017-07-31             팔레트 (Feat. G-DRAGON)      25
29 2017-07-31                  사랑이 잘 (With 오혁)      38
30 2017-07-31                             이 지금      54
31 2017-07-31                            이런 엔딩      87
32 2017-08-31                              밤편지      16
33 2017-08-31             팔레트 (Feat. G-DRAGON)      43
34 2017-08-31                  사랑이 잘 (With 오혁)      59
35 2017-08-31                             이 지금      72
36 2017-08-31                            이런 엔딩      94

In [5]:
chart['ranking'] = pd.to_numeric( chart['ranking'] )
chart_pivot = pd.pivot_table(chart, index='date', columns='title')
chart_pivot

             ranking                                                      \
title      Black Out 그렇게 사랑은   마침표 미리 메리 크리스마스 (feat. 천둥 Of MBLAQ)   밤편지
date
2016-01-31       NaN     NaN   NaN                             NaN   NaN
2016-02-29       NaN     NaN   NaN                             NaN   NaN
2016-11-30       NaN     NaN   NaN                            67.0   NaN
2016-12-31       NaN     NaN   NaN                            85.0   NaN
2017-03-31       NaN     NaN   NaN                             NaN   2.0
2017-04-30      18.0    44.0  33.0                             NaN  10.0
2017-05-31       NaN     NaN   NaN                             NaN  29.0
2017-06-30       NaN     NaN   NaN                             NaN  32.0
2017-07-31       NaN     NaN   NaN                             NaN  12.0
2017-08-31       NaN     NaN   NaN                             NaN  16.0


title      사랑이 잘 (With 오혁)   스물셋  이 지금 이런 엔딩   이름에게    잼잼 팔레트 (Feat. G-DRAGON)
date
2016-01-31             NaN  53.0   NaN   NaN    NaN   NaN                  NaN
2016-02-29             NaN  69.0   NaN   NaN    NaN   NaN                  NaN
2016-11-30             NaN   NaN   NaN   NaN    NaN   NaN                  NaN
2016-12-31             NaN   NaN   NaN   NaN    NaN   NaN                  NaN
2017-03-31             NaN   NaN   NaN   NaN    NaN   NaN                  NaN
2017-04-30             5.0   NaN   4.0   9.0   14.0  11.0                  1.0
2017-05-31            22.0   NaN  31.0  45.0  100.0  67.0                 13.0
2017-06-30            41.0   NaN  63.0  89.0    NaN   NaN                 23.0
2017-07-31            38.0   NaN  54.0  87.0    NaN   NaN                 25.0
2017-08-31            59.0   NaN  72.0  94.0    NaN   NaN                 43.0